name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
      - name: Build
        run: poetry build
